"""
Daily nutrition tips, pre-written natively per language (not machine-translated
from English at send-time). Structure: TIPS[language][category] -> list[str].

⚠️ DATA QUALITY NOTE — read before shipping "yoruba" to real users:
The "hausa" and "igbo" sections read as genuinely fluent, native text.
The "yoruba" section, however, has multiple entries with Hausa/Igbo words
mixed into otherwise-Yoruba sentences (e.g. "giúp kwakwalwa", "Maimakon",
"Gwada biskit", "mgbe o mụ́rọ̀ tán", "Zere inye nwa gị", "Tụọ arọ ... sarị",
"Daka ha daadaa tàbí hazie n'ofe") — this looks like leftover contamination
from whatever translation pipeline produced it, not clean Yoruba. At least
one line in every single category (TIPS_PREGNANT, TIPS_BREASTFEEDING,
TIPS_BABY_0_6, TIPS_BABY_6_12, TIPS_BABY_12_24) is affected.
Recommend regenerating/reviewing the "yoruba" list with a native speaker
before sending it to real users — it will look confusing/wrong to a Yoruba
reader in its current state, the same way the old NLLB output did.

📌 2026-08-25: added a further batch of tips to every category in every
language (roughly doubling TIPS_PREGNANT/TIPS_BREASTFEEDING, and adding
4-6 more entries each to the baby-age categories) — this was to reduce how
often the same tip repeats for a given user, on top of the anti-repeat
logic in app.py's _send_daily_tips(). The new English entries are solid.
The new hausa/igbo/yoruba entries were written carefully (plain, non-idiomatic
phrasing, reusing vocabulary already present elsewhere in this file) to
avoid the kind of cross-language contamination described above, but — same
as the rest of this file — they have NOT been reviewed by a native speaker
and should get that pass before being treated as fully trustworthy.
"""

TIPS = {
  "english": {
    "TIPS_PREGNANT": [
      "Eating iron-rich foods like beans, liver, and dark green vegetables every day helps prevent tiredness and supports your baby's development.",
      "Folate is very important in pregnancy — eat cowpea (beans) and dark leafy vegetables like ugu daily to help your baby's brain and spine grow well.",
      "Your body needs more food when you are pregnant. Try to eat one extra small meal or snack every day — groundnut, egg, or fruit are all good choices.",
      "Drinking enough water every day — at least 8 glasses — keeps you hydrated, prevents constipation, and supports your overall health during pregnancy.",
      "Palm oil in your soups is a good source of Vitamin A, which supports your baby's eyesight and immune system.",
      "Eating a variety of foods every day — grains, beans, vegetables, fruit, and small portions of meat or fish — gives your baby the best start.",
      "Calcium helps your baby's bones grow strong. Try to include milk, yoghurt, crayfish, or soybean in your meals regularly.",
      "Avoid drinking tea or coffee with your meals — they can reduce how much iron your body absorbs. Instead, add a squeeze of lemon or orange.",
      "Rest is just as important as food during pregnancy. Try to sleep at least 8 hours a night and rest during the day when you can.",
      "If you feel very tired, dizzy, or short of breath, visit your nearest health centre — these can be signs of anaemia which is common in pregnancy.",
      "Eating small, frequent meals throughout the day helps if you feel nauseous. Try dry biscuit or plain pap in the morning before eating a bigger meal.",
      "Your baby needs iodine for brain development. Use iodised salt in your cooking — it is affordable and available in most markets.",
      "Zinc helps your baby grow and supports your immune system. Beans, beef, and crayfish are affordable Nigerian sources of zinc.",
      "Vitamin C helps your body absorb iron better. Adding tomato, pepper, or orange to your meals is a simple way to get more from your food.",
      "Avoid eating very salty or very sugary foods often during pregnancy. They can cause swelling and are not good for your baby.",
      "Wash your hands with soap before eating and before preparing food — this helps prevent infections that can affect you and your baby during pregnancy.",
      "Take your iron and folic acid tablets every day as given by your health worker, even if you feel well — they help prevent anaemia and support your baby's growth.",
      "Getting a little sunlight on your skin each day helps your body make Vitamin D, which is important for your bones and your baby's bones too.",
      "Make sure meat, fish, and eggs are well cooked before eating — undercooked food can carry germs that are riskier during pregnancy.",
      "Attend your antenatal clinic visits as scheduled — they help catch problems early and are a good time to ask about your diet and any symptoms.",
      "Cravings for unusual things like clay or chalk (pica) can be a sign of low iron. Speak to your health worker rather than eating these.",
      "If the hospital prescribed MMS (multiple micronutrient supplement) tablets for you, please don't forget to take one every day — it gives you and your baby vitamins and minerals that food alone may not fully cover.",
      "Try to take your MMS multivitamin at the same time each day so it becomes part of your routine — many mothers find it easiest right after a meal.",
      "Taking your MMS tablet with food, or just before bed, can help if it makes you feel a little nauseous. Don't stop taking it — speak to your health worker instead.",
      "Keep taking your MMS multivitamin every day even when you feel perfectly well. It is protecting your baby's growth quietly in the background, not just treating symptoms.",
      "Your MMS multivitamin works alongside good meals — it does not replace them. Keep eating your beans, vegetables, fruit, and protein as well as taking the tablet.",
      "If your MMS multivitamin tablets are finishing or you have run out, ask for more at your next antenatal visit — try not to skip days in between."
    ],
    "TIPS_BREASTFEEDING": [
      "Breast milk is the best food for your baby in the first 6 months — it contains everything your baby needs, including antibodies that fight infection.",
      "Breastfeeding frequently is the most important thing you can do to keep your milk supply high. Drink enough water to satisfy your thirst to stay healthy.",
      "Breastfeed your baby on demand — whenever they show signs of hunger like rooting or sucking their fists. The more you feed, the more milk your body makes.",
      "Eating groundnut soup with ugu or waterleaf regularly can help support your milk supply. These foods are rich in nutrients your body needs for breastfeeding.",
      "Do not give your baby water, pap, or any other food or drink before 6 months — breast milk alone is enough, even in hot weather.",
      "Your baby is getting enough milk if they are gaining weight steadily and have at least 6 wet nappies a day.",
      "Palm oil in your soups provides Vitamin A which passes into your breast milk and protects your baby's eyes and immune system.",
      "Eating protein every day — beans, fish, egg, or meat — helps your body produce enough milk and keeps you strong.",
      "If your breasts feel very hard or sore, feed your baby more often. This relieves engorgement and keeps your milk flowing.",
      "Tiger nut milk and fura da nono are traditional Nigerian drinks that many nursing mothers find helpful for maintaining milk supply.",
      "Breastfeeding helps your uterus return to its normal size after birth and reduces your risk of certain cancers — it is good for you too, not just your baby.",
      "Continue breastfeeding alongside solid foods from 6 months until your baby is at least 2 years old — breast milk still provides important nutrients and protection.",
      "Iron-rich foods like beans, liver, and sardines are especially important for breastfeeding mothers. Many Nigerian mothers have low iron after childbirth.",
      "Calcium keeps your bones strong while you are breastfeeding. Crayfish, soybean products, milk, and yoghurt are affordable local sources.",
      "If you need to go out or return to work, you can express your breast milk and store it safely for your baby — ask your nearest health worker how.",
      "Wash your hands with soap before every breastfeed and before preparing your baby's food — simple hygiene protects both of you from infection.",
      "Feeling stressed or worried can temporarily reduce your milk flow. Try to rest, breathe slowly, and ask family for support when you can.",
      "There's no need for a special diet to make good milk — just eat a variety of the foods available to you and drink water when thirsty.",
      "If you're taking any medicine, ask your health worker whether it's safe during breastfeeding — most common medicines are fine.",
      "Cracked or sore nipples usually mean your baby isn't latching well. Ask a health worker to check your baby's positioning — it gets easier with the right latch."
    ],
    "TIPS_BABY_0_6": [
      "Breast milk is all your baby needs for the first 6 months — no water, no pap, no formula. It protects against infection and supports brain development.",
      "Breastfeed your baby at least 8 to 12 times every 24 hours in the early weeks — frequent feeding builds your milk supply.",
      "Hold your baby skin-to-skin as much as possible. It keeps them warm, calm, and encourages breastfeeding.",
      "Your baby's brain is growing very fast right now. Breast milk contains all the fats and nutrients needed for healthy brain development.",
      "Never add sugar, honey, or salt to anything you give your baby under 6 months. Their kidneys and digestive system are not ready for these.",
      "If your baby is sleeping longer than 4 hours at a stretch in the early weeks, wake them for a feed — they need to eat frequently to grow well.",
      "Breast milk changes throughout the day and as your baby grows — your body is constantly adjusting the milk to meet your baby's exact needs.",
      "Wash your hands with soap before touching or feeding your baby — their immune system is still developing and hygiene matters a lot in these early months.",
      "A crying baby isn't always hungry — they may need a nappy change, comfort, or simply to be held. Get to know your baby's different cries over time.",
      "There is no need to give gripe water, herbal mixtures, or teething remedies before 6 months — breast milk alone meets all your baby's needs.",
      "Tummy time while your baby is awake and supervised helps build the neck and shoulder strength they'll need later for sitting and crawling.",
      "If your baby has a fever, is feeding poorly, or seems unusually sleepy or floppy, take them to a health centre right away — don't wait it out at home."
    ],
    "TIPS_BABY_6_12": [
      "Your baby is ready to start solid foods at 6 months alongside breast milk. Start with soft mashed foods like pap, mashed yam, or mashed beans.",
      "Offer your baby solid foods 2 to 3 times a day between 6 and 8 months, increasing to 3 to 4 times a day by 9 months.",
      "Adding a small amount of palm oil or groundnut paste to your baby's pap gives them important fats and extra energy for growth.",
      "Introduce one new food at a time and wait 2 to 3 days before adding another — this helps you spot any foods that upset your baby's stomach.",
      "By 8 months, most babies can manage soft finger foods — try small pieces of soft fruit, boiled carrot, or mashed egg yolk.",
      "Mashed egg yolk is one of the best foods you can give your baby from 6 months — it is rich in protein, iron, and healthy fat.",
      "Mashed or blended crayfish added to your baby's pap provides calcium and protein. A small pinch is enough.",
      "Breast milk is still very important between 6 and 12 months — continue breastfeeding alongside solid meals.",
      "Your baby needs to eat from at least 5 different food groups every day. Try to include grains, beans or eggs, vegetables, fruit, and a little meat or fish.",
      "Avoid giving your baby tea, juice, soft drinks, or any sweetened drinks — water and breast milk are the only drinks they need.",
      "Pureed liver once or twice a week is one of the best foods for babies — it is rich in iron, zinc, and Vitamin A. Mash it very well.",
      "If your baby turns away or closes their mouth, do not force them to eat. Try again later or offer a different food.",
      "Wash your hands and clean your baby's eating area before every meal — germs from dirty hands or utensils are a common cause of diarrhoea at this age.",
      "Start with thin, smooth purees and gradually move to thicker, mashed textures as your baby gets used to eating — this helps them learn to chew.",
      "Iodised salt in small amounts in your baby's food is fine from 6 months and supports healthy brain development, but avoid adding extra salt or sugar beyond that.",
      "Offer your baby water in a cup with meals from 6 months, in small sips — this is separate from breast milk and helps them get used to cup drinking.",
      "Store any prepared food for your baby in a clean, covered container and use it within a few hours — do not reheat food more than once.",
      "If your baby has diarrhoea or vomiting, keep breastfeeding and offer small sips of clean water often — seek care quickly if it doesn't improve."
    ],
    "TIPS_BABY_12_24": [
      "By 12 months your baby can eat most family foods — just make sure meals are soft, not too salty, and cut into small pieces they can manage.",
      "Continue breastfeeding alongside family foods until your baby is at least 2 years old. Breast milk still provides important nutrition and protection.",
      "Offer your baby 3 main meals and 1 to 2 healthy snacks every day. Fruit, boiled egg, or groundnut are good snack options.",
      "Animal-source foods like egg, fish, chicken, or liver at least once a day help your baby's brain and body grow well.",
      "Dark green vegetables like ugu, spinach, and waterleaf are rich in iron and Vitamin A. Add them to your baby's soups and stews every day.",
      "Avoid giving your baby biscuits, sweets, fried snacks, or sugary drinks — these fill them up without giving any real nutrition.",
      "Your baby needs variety — try to offer different foods each day so they learn to enjoy a wide range of tastes and get all the nutrients they need.",
      "Orange and yellow fruits and vegetables like pawpaw, mango, and carrot are rich in Vitamin A which protects your baby's eyesight and immunity.",
      "Weigh your baby every month at your nearest health centre to make sure they are growing well. Bring your health card each time.",
      "If your baby refuses a new food, keep offering it in small amounts — babies often need to see a food 8 to 10 times before they accept it.",
      "Beans, cowpea, and soybean are affordable protein foods that are great for your baby's growth. Mash them well or blend into soups.",
      "Cow milk, yoghurt, or nono can be given as part of meals from 12 months — they provide calcium and protein for strong bones.",
      "Let your toddler try to feed themselves with their hands or a spoon, even if it's messy — this builds independence and a healthy relationship with food.",
      "Wash fruits and vegetables well and wash your hands before preparing your toddler's meals to reduce the risk of stomach infections.",
      "Plantain, yam, and cassava are good energy foods for a growing toddler — pair them with beans, egg, or fish for a more complete meal.",
      "Avoid giving your toddler whole nuts, popcorn, or hard raw vegetables that could cause choking — cut food into small, soft pieces instead.",
      "If your toddler seems to be eating less than usual, is unusually tired, or isn't gaining weight, take them to your health centre for a check-up.",
      "Try not to use food as a reward or punishment — this can create unhealthy eating habits later. Praise your toddler simply for trying new foods."
    ]
  },
  "hausa": {
    "TIPS_PREGNANT": [
      "Cin abinci mai arzikin karfe (iron) kamar wake, hanta, da ganyayyaki masu duhu kowace rana yana taimakawa wajen kiyaye gajiya da tallafawa ci gaban jaririnki.",
      "Folate yana da muhimmanci sosai a lokacin daukar ciki — ci wake da ganyayyaki kamar ugu kowace rana don taimakawa kwakwalwa da kashin baya na jaririnki girma sosai.",
      "Jikinki yana buƙatar abinci mai yawa lokacin da kike da juna biyu. Yi ƙoƙarin cin abinci guda ɗaya na daban ko kayan ciye-ciye kowace rana — gyaɗa, ƙwai, ko 'ya'yan itace duka zaɓuɓɓuka ne masu kyau.",
      "Shan ruwa mai yawa kowace rana — aƙalla kofuna 8 — yana kiyaye miki lafiya, yana kare maƙarƙashiya, yana kuma taimakawa jikinki gaba ɗaya.",
      "Man ja a cikin miyarki kyakkyawan tushen Vitamin A ne, wanda yake tallafawa idanun jaririnki da garkuwar jikinsa.",
      "Cin abinci iri-iri kowace rana — hatsi, wake, kayan lambu, 'ya'yan itace, da ƙananan rabon nama ko kifi — yana ba jaririnki mafi kyawun farawa.",
      "Calcium yana taimakawa ƙashin jaririnki girma da ƙarfi. Yi ƙoƙarin haɗawa da madara, yoghurt, crayfish, ko waken soya a abinci a kai a kai.",
      "Guje wa shan shayi ko kofi tare da abincinki — suna iya rage adadin ƙarfen (iron) da jikinki ke ɗauka. Maimakon haka, ƙara matse lemon tsami ko lemo.",
      "Huta yana da muhimmanci kamar abinci lokacin daukar ciki. Yi ƙoƙarin barci a ƙalla sa'o'i 8 a dare kuma ka huta a rana lokacin da za ka iya.",
      "Idan kina jin gajiya sosai, jiri, ko matsalar lumfashi, ziyarci cibiyar lafiya mafi kusa — wadannan na iya zama alamomin karancin jini (anaemia).",
      "Cin abinci kaɗan-kaɗan akai-akai a tsawon rana yana taimakawa idan kina jin tashin zuciya. Gwada busassun biskit ko koko kafin cin babban abinci.",
      "Jaririnki yana buƙatar iodine don ci gaban kwakwalwa. Yi amfani da gishiri mai iodine a girkin ku — yana da araha kuma yana samuwa a kasuwanni.",
      "Zinc yana taimakawa jaririnki girma yana kuma tallafawa garkuwar jikinki. Wake, nama, da crayfish sune hanyoyin samun zinc mai araha a Najeriya.",
      "Vitamin C yana taimakawa jikinki jan ƙarfe (iron) da kyau. Ƙara tumatir, barkono, ko lemo a abincinki hanya ce mai sauƙi ta samun alfanu daga abinci.",
      "Guje wa cin abinci mai gishiri sosai ko mai zaƙi sosai a kai a kai lokacin daukar ciki. Suna iya haifar da kumburi kuma ba su da kyau ga jaririnki.",
      "Wanke hannuwanki da sabulu kafin cin abinci da kafin girki — wannan yana taimakawa wajen kare ki da jaririnki daga cututtuka a lokacin daukar ciki.",
      "Sha kwayoyin ƙarfe (iron) da folic acid kowace rana kamar yadda ma'aikacin lafiya ya bayar, ko da kina jin lafiya — suna taimakawa wajen kare ki daga karancin jini kuma suna tallafawa ci gaban jaririnki.",
      "Samun kaɗan hasken rana a jikinki kowace rana yana taimakawa jikinki samar da Vitamin D, wanda yake da muhimmanci ga ƙashinki da na jaririnki.",
      "Tabbatar an dafa nama, kifi, da ƙwai sosai kafin cin su — abinci marar cikakken dafuwa na iya ɗauke da kwayoyin cuta masu haɗari a lokacin daukar ciki.",
      "Halarci duk ziyarar kula da ciki (antenatal) kamar yadda aka tsara — suna taimakawa gano matsala da wuri kuma lokaci ne mai kyau don yin tambaya game da abincinki.",
      "Idan kina jin sha'awar cin abubuwa kamar yumɓu ko alli, wannan na iya zama alamar karancin ƙarfe (iron). Tuntuɓi ma'aikacin lafiya maimakon cin irin waɗannan abubuwan.",
      "Idan asibiti ya rubuta miki kwayoyin MMS (multiple micronutrient supplement), kada ki manta shan guda ɗaya kowace rana — suna ba ki da jaririnki bitamin da ma'adanai da abinci kaɗai ba zai iya samarwa gaba ɗaya ba.",
      "Yi ƙoƙarin shan kwayar MMS ɗinki a lokaci ɗaya kowace rana don ya zama wani ɓangare na al'adarki — yawancin mata suna ganin ya fi sauƙi nan da nan bayan cin abinci.",
      "Shan kwayar MMS tare da abinci, ko kafin kwanciya barci, na iya taimakawa idan tana sa ki jin tashin zuciya. Kada ki daina sha — maimakon haka, tuntuɓi ma'aikacin lafiya.",
      "Ci gaba da shan kwayar MMS kowace rana ko da kina jin lafiya sosai. Tana kare ci gaban jaririnki a hankali, ba wai kawai maganin alamun rashin lafiya ba ce.",
      "Kwayar MMS ɗinki tana aiki tare da abinci mai kyau — ba ta maye gurbinsa ba. Ci gaba da cin wake, kayan lambu, 'ya'yan itace, da abinci mai gina jiki tare da shan kwayar.",
      "Idan kwayoyin MMS ɗinki suna ƙarewa ko sun ƙare, nemi ƙarin a ziyararki ta gaba ta kula da ciki — yi ƙoƙarin kada ki tsallake kwanaki a tsakani."
    ],
    "TIPS_BREASTFEEDING": [
      "Nonon uwa shi ne mafi kyawun abinci ga jaririnki a cikin watanni 6 na farko — yana ɗauke da duk abin da jaririnki yake buƙata, har da sinadaran kare jiki daga cututtuka.",
      "Nayar da jaririnki nono akai-akai shi ne babban abin da ke ƙara fitowar nono. Ki tabbatar kina shan ruwa gwargwadon buƙatar ƙushirwarki don kiyaye lafiyarki.",
      "Bawa jaririnki nono duk lokacin da ya nuna alamun jin yunwa — kamar juyar da kai ko tsotsar hannunsa. Gwargwadon yadda kike ba shi nono, shi ne jikinki zai riƙa fitar da shi da yawa.",
      "Cin miyar ugu ko waterleaf da aka fiɗa da man ja da kaɗan daga gyada yana taimakawa wajen samar da sinadaran da jiki ke buƙata don fitar da nono.",
      "Kada ki bawa jaririnki ruwa, koko, ko wani abinci kafin watanni 6 — nonon uwa kaɗai ya wadatar, ko da a lokacin zafi ne.",
      "Jaririnki yana samun nono daidai idan yana ƙara nauyi kuma yana tsula fitsari aƙalla sau 6 a rana.",
      "Man ja a cikin miyarki yana samar da Vitamin A wanda yake shiga cikin nononki yana kare idanun jaririnki da ƙarfafa garkuwar jikinsa.",
      "Cin abinci mai gina jiki (protein) kowace rana — kamar waƙa, kifi, ƙwai, ko nama — yana taimakawa jikinki wajen samar da nono mai kyau da kiyaye ƙarfinki.",
      "Idan nononki ya kumbura ko yake miki ciwo, ki bawa jaririnki nono akai-akai. Wannan yana rage matsi yana sa nonon fitowa yadda ya kamata.",
      "Kunan aya da fura da nono abubuwan sha ne na gargajiya da suke taimakawa mata masu shayarwa wajen kiyaye fitowar nono.",
      "Shayar da nono yana taimakawa mahaifarki komawa yadda take bayan haihuwa kuma yana rage haɗarin kamuwa da ciwon daji (cancer) — yana da amfani gare ki ba kawai jaririnki ba.",
      "Ci gaba da shayar da nono tare da abinci daga watanni 6 har zuwa shekaru 2 ko fiye — nonon uwa yana ci gaba da samar da muhimman sinadirai da kariya.",
      "Abinci mai ƙarfe (iron) kamar waƙa, hanta, da kifin sardine suna da muhimmanci sosai ga mata masu shayarwa bayan haihuwa.",
      "Sinadarin Calcium yana kiyaye ƙafafuki da ƙashinki da ƙarfi. Yana samuwa a cikin yakuwa, crayfish, waken soya, da nono.",
      "Idan za ki fita ko komawa wajen aiki, za ki iya matse nononki ki adana shi lami lafiya ga jaririnki — ki tambayi ma'aikacin lafiya domin samun bayani.",
      "Wanke hannuwanki da sabulu kafin kowace shayarwa da kafin shirya abincin jaririnki — tsafta mai sauƙi tana kare ku biyu daga cututtuka.",
      "Jin damuwa ko tsoro na iya rage fitowar nononki na ɗan lokaci. Yi ƙoƙarin huta, ki ja numfashi a hankali, ki kuma nemi taimakon iyali lokacin da za ki iya.",
      "Babu buƙatar abinci na musamman don samun nono mai kyau — kawai ci abinci iri-iri da kike samu ki kuma sha ruwa lokacin da kike jin ƙishirwa.",
      "Idan kina shan wani magani, tambayi ma'aikacin lafiya ko yana da lafiya a lokacin shayarwa — yawancin magunguna na kowa suna da lafiya.",
      "Idan nononki ya tsage ko yana yi miki ciwo, yawanci yana nufin jaririnki ba ya kamewa daidai. Nemi ma'aikacin lafiya ya duba matsayin jaririnki."
    ],
    "TIPS_BABY_0_6": [
      "Nonon uwa shi ne kawai abin da jaririnki ke buƙata a cikin watanni 6 na farko — babu ruwa, babu koko, babu madarar gwangwani. Yana kariya daga cututtuka kuma yana tallafawa ci gaban kwakwalwa.",
      "Shayar da jaririnki nono aƙalla sau 8 zuwa 12 a duk sa'o'i 24 a farkon makonni — shayarwa akai-akai yana gina adadin nononki.",
      "Rƙe jaririnki fata-da-fata gwargwadon iko. Yana sa su ji ɗumi, kwanciyar hankali, kuma yana ƙarfafa shayarwa.",
      "Kwakwalwar jaririnki tana girma da sauri sosai a yanzu. Nonon uwa yana ɗauke da duk mai da sinadaran da ake buƙata don samun ci gaban kwakwalwa mai lafiya.",
      "Kada ka taɓa ƙara suga, zuma, ko gishiri a kan duk abin da kuke ba jaririnki ƙasa da watanni 6. Ƙodan su da tsarin abincinsu ba a shirye suke ba.",
      "Idan jaririnki yana barci fiye da sa'o'i 4 a jere a cikin farkon makonni, tashe su don ciyarwa — suna buƙatar cin abinci akai-akai don girma da kyau.",
      "Nonon uwa yana canzawa a cikin yini kuma yayin da jaririnki ke girma — jikinki yana canza abun ciki akai-akai don biyan buƙatun jaririnki.",
      "Wanke hannuwanki da sabulu kafin taɓawa ko ciyar da jaririnki — garkuwar jikinsa tana cikin gina kai kuma tsafta tana da muhimmanci sosai a wannan lokacin.",
      "Jaririn da yake kuka ba koyaushe yana nufin yunwa ba — wataƙila yana buƙatar sauya diaper, ta'aziyya, ko kawai a riƙe shi. Za ki koyi bambancin kukan jaririnki da lokaci.",
      "Babu buƙatar bawa jaririnki ruwan ganye, magungunan gargajiya, ko maganin haƙori kafin watanni 6 — nonon uwa kaɗai ya wadatar da duk buƙatunsa.",
      "Idan jaririnki yana da zazzabi, yana wahalar shan nono, ko yana yin sanyi ba tare da ƙarfi ba, kai shi asibiti nan take — kada ki jira a gida."
    ],
    "TIPS_BABY_6_12": [
      "Jaririnki ya shirya don fara ingantaccen abinci a watanni 6 tare da nonon uwa. Fara da abinci mai laushi kamar koko, dakasshen doya, ko daka wake.",
      "Bawa jaririnki ingantaccen abinci sau 2 zuwa 3 a rana tsakanin watanni 6 zuwa 8, yana ƙaruwa zuwa sau 3 zuwa 4 a rana zuwa watanni 9.",
      "Ƙara ƙanƙanen adadin man ja ko man gyaɗa a kokon jaririnki yana ba su muhimman mai da ƙarin ƙarfi don girma.",
      "Gabatar da abinci sabo guda ɗaya a lokaci guda kuma jira kwanaki 2 zuwa 3 kafin ƙara wani — wannan yana taimaka muku gane abincin da ke ɓata ciki.",
      "Zuwa watanni 8, yawancin jarirai suna iya sarrafa abincin yatsa mai laushi — gwada ƙananan guntun 'ya'yan itace masu laushi, tafasasshen karas, ko gwanin ƙwai.",
      "Gwanin ƙwai da aka daka yana ɗaya daga cikin mafi kyawun abincin da za ku iya bawa jaririnki daga watanni 6 — yana da wadata a cikin protein, iron, da mai mai kyau.",
      "Dakan crayfish da aka ƙara a kokon jaririnki yana samar da calcium da protein. Ƙananan tsunkule ya wadatar.",
      "Nonon uwa yana da muhimmanci sosai tsakanin watanni 6 zuwa 12 — ci gaba da shayar da nono tare da abinci.",
      "Jaririnki yana buƙatar cin abinci daga aƙalla rukunin abinci 5 daban-daban kowace rana. Yi ƙoƙarin haɗawa da hatsi, wake ko ƙwai, kayan lambu, 'ya'yan itace, da kaɗan daga nama ko kifi.",
      "Guje wa bawa jaririnki shayi, ruwan 'ya'yan itace, abin sha mai zaƙi — ruwa da nonon uwa sune kaɗai abubuwan sha da suke buƙata.",
      "Dakan hanta sau ɗaya ko sau biyu a mako yana ɗaya daga cikin mafi kyawun abinci ga jarirai — yana da arzikin iron, zinc, da Vitamin A. Daka shi sosai.",
      "Idan jaririnki ya juya kai ko ya rufe bakinsa, kada ki tilasta masa cin abinci. Gwada sake daga baya ko ba shi abinci daban.",
      "Wanke hannuwanki ki kuma tsaftace wurin cin abincin jaririnki kafin kowane abinci — ƙwayoyin cuta daga hannaye ko kayan aiki marasa tsabta na iya haifar da gudawa a wannan shekarun.",
      "Fara da abinci mai laushi sosai sannan a hankali ka koma zuwa abinci mai ɗan kauri yayin da jaririnki ke saba da ci — wannan yana taimaka masa koyon taunawa.",
      "Ƙaramin gishirin iodine a abincin jaririnki daga watanni 6 yana da lafiya kuma yana tallafawa ci gaban kwakwalwa, amma guji ƙarin gishiri ko sukari fiye da haka.",
      "Bawa jaririnki ruwa a cikin kofi cikin ƙananan sips a lokacin cin abinci daga watanni 6 — wannan daban yake da nonon uwa kuma yana taimaka masa saba da shan ruwa daga kofi.",
      "Ajiye duk abincin da aka shirya wa jaririnki a cikin tsaftataccen akwati mai murfi kuma a yi amfani da shi cikin 'yan sa'o'i — kada a sake dumama abinci fiye da sau ɗaya."
    ],
    "TIPS_BABY_12_24": [
      "Zuwa watanni 12 jaririnki yana iya cin mafi yawan abincin iyali — kawai tabbatar abincin yana da laushi, ba shi da gishiri sosai, kuma an yanka shi ƙananan guntu.",
      "Ci gaba da shayar da nono tare da abincin iyali har tsawon shekaru 2 ko fiye. Nonon uwa har yanzu yana samar da abinci mai gina jiki da kariya.",
      "Bawa jaririnki babban abinci sau 3 da kayan ciye-ciye masu kyau sau 1 zuwa 2 kowace rana. 'Ya'yan itace, tafasasshen ƙwai, ko gyaɗa kyawawan zaɓuɓɓuka ne.",
      "Abinci daga dabbobi kamar ƙwai, kifi, kaza, ko hanta aƙalla sau ɗaya a rana yana taimakawa kwakwalwar jaririnki da jikinsa girma da kyau.",
      "Kayan lambu masu duhu kamar ugu, alayyahu, da waterleaf suna da arzikin iron da Vitamin A. Ƙara su a miyar jaririnki kowace rana.",
      "Guje wa bawa jaririnki biskit, alwasa, abincin soyayye, ko abin sha mai zaƙi — wadannan suna cika cikinsu ba tare da ba su ingantaccen abinci ba.",
      "Jaririnki yana buƙatar bambancin abinci — yi ƙoƙarin bawa abinci daban-daban kowace rana don su koyi jin daɗin ɗanɗano iri-iri.",
      "Kayan itatuwa da kayan lambu masu launin ruwan gwal da rawaya kamar gwanda, mangwaro, da karas suna da arzikin Vitamin A wanda ke kare idanu da garkuwar jiki.",
      "Auna nauyin jaririnki kowane wata a cibiyar lafiya mafi kusa don tabbatar da suna girma da kyau. Ku zo da katin lafiyarku kowane lokaci.",
      "Idan jaririnki ya ƙi sabon abinci, ci gaba da ba shi a ƙananan adadi — jarirai galibi suna buƙatar ganin abinci sau 8 zuwa 10 kafin su karɓa.",
      "Wake, cowpea, da waken soya abinci ne mai araha na protein wanda ke da kyau ga girman jaririnki. Daka su sosai ko haɗa a miya.",
      "Madara, yoghurt, ko nono za a iya ba da su a matsayin wani ɓangare na abinci daga watanni 12 — suna samar da calcium da protein ga ƙashi.",
      "Ka yaronki ya gwada ciyar da kansa da hannu ko cokali, ko da zai zube — wannan yana gina 'yancin kai da kyakkyawar dangantaka da abinci.",
      "Wanke 'ya'yan itace da kayan lambu sosai ki kuma wanke hannuwanki kafin shirya abincin yaronki don rage haɗarin cututtukan ciki.",
      "Ayaba, doya, da rogo abinci ne masu kyau na samar da ƙarfi ga yaro mai girma — haɗa su da wake, ƙwai, ko kifi don cikakken abinci.",
      "Guji bawa yaronki cikakken gyaɗa, popcorn, ko danyen kayan lambu masu wuya waɗanda za su iya sa shi shaƙa — a maimakon haka, yanka abinci kanana kuma masu laushi.",
      "Idan yaronki yana cin abinci kaɗan fiye da yadda aka saba, yana gajiya sosai, ko ba ya ƙara nauyi, kai shi asibiti don a duba shi."
    ]
  },
  "igbo": {
    "TIPS_PREGNANT": [
      "Iri nri nwere iron dịka agwa, chi (liver), na akwụkwọ nri ndụ kwa ụbọchị na-enyere aka igbochi ike ọgwụgwụ ma na-akwado uto nwa gị.",
      "Folate dị mkpa nke ukwuu n'ime ime — na-eri agwa na akwụkwọ nri dịka ugu kwa ụbọchị iji nyere ụbụrụ na ọkpụkpụ azụ nwa gị aka itolite nke ọma.",
      "Ahụ gị chọrọ nri karịa mgbe ị dị ime. Gbalịa rie obere nri ọzọ ma ọ bụ nri mfe kwa ụbọchị — ahụekere, ọkụkọ/ọkwá, ma ọ bụ mkpụrụ osisi bụ nhọrọ mma.",
      "Ịṅụ mmiri nke ọma kwa ụbọchị — dịkarịa ala iko 8 — na-edobe gị ahụ ike, na-egbochi fitọ ma na-akwado ahụ ike gị dum.",
      "Mmanụ nri (mmanụ anwụ) n'ofe gị bụ ezigbo ebe si enweta Vitamin A, nke na-akwado nhụjuanya auga nwa gị na usoro nchebe ahụ.",
      "Iri nri dị iche iche kwa ụbọchị — ọka, agwa, akwụkwọ nri, mkpụrụ osisi, na obere anụ ma ọ bụ azụ — na-enye nwa gị mmalite kachasị mma.",
      "Calcium na-enyere ọkpụkpụ nwa gị aka itolite ike. Gbalịa tinye mmiri ara, yoghurt, crayfish, ma ọ bụ soybean n'nri gị mgbe niile.",
      "Zere ịṅụ tii ma ọ bụ kọfị na nri gị — ha nwere ike belata adịghị nke iron ahụ gị na-amịpụta. Maimakon nke ahụ, tinye obere mmiri lemon ma ọ bụ oroma.",
      "Izu ike dị mkpa dịka nri n'oge ime. Gbalịa hie ụra dịkarịa ala saịnsị 8 n'abali ma zuo ike n'ehihie mgbe ị nwere ike.",
      "Ọ bụrụ na ị na-enwe oke ike ọgwụgwụ, isi mgbaka, ma ọ bụ ume mfu, gaa n'ụlọ ọrụ ahụ ike kacha nso — ndị a nwere ike ịbụ akara nke anemia.",
      "Iri obere nri ugboro ugboro n'ụbọchị na-enyere aka ma ọ bụrụ na ị na-enwe mmetụta nsogbu afọ. Gwada biskit mfe ma ọ bụ pap n'ụtụtụ tupu ị rie nri buru ibu.",
      "Nwa gị chọrọ iodine maka uto ụbụrụ. Jiri nnu nwere iodine mee nri gị — ọ dị ọnụ ala ma dị n'ahịa gasi.",
      "Zinc na-enyere nwa gị aka itolite ma na-akwado usoro nchebe ahụ gị. Agwa, anụ ehi, na crayfish bụ ebe ndị dị ọnụ ala na Naijiria iji nweta zinc.",
      "Vitamin C na-enyere ahụ gị aka amịpụta iron nke ọma. Itinye tomato, ose, ma ọ bụ oroma n'nri gị bụ ụzọ mfe iji nweta karịa n'nri gị.",
      "Zere iri nri nwere nnu nke ukwuu ma ọ bụ shuga nke ukwuu n'oge ime. Ha nwere ike ibute ọvụvụ ma ha adịghị mma maka nwa gị.",
      "Kwọwa aka gị na ncha tupu i righde nri ma ọ bụ tupu ịkwadebe nri — nke a na-enyere aka igbochi ọrịa nke nwere ike imetụta gị na nwa gị n'oge ime.",
      "Na-aṅụ ọgwụ iron na folic acid gị kwa ụbọchị dịka onye ọrụ ahụike nyere gị, ọbụna mgbe ị dị mma — ha na-enyere aka igbochi anemia ma na-akwado uto nwa gị.",
      "Inweta obere anwụ n'ahụ gị kwa ụbọchị na-enyere ahụ gị aka ime Vitamin D, nke dị mkpa maka ọkpụkpụ gị na nke nwa gị.",
      "Jide ka a sie anụ, azụ, na akwa nke ọma tupu i rie ha — nri esighị esi nke ọma nwere ike ịbụ ihe ize ndụ n'oge ime.",
      "Gaa na nleta antenatal gị dịka a hazibu ya — ha na-enyere aka chọpụta nsogbu n'oge ma bụrụkwa oge dị mma iji jụọ ajụjụ gbasara nri gị.",
      "Ọ bụrụ na ị na-achọ iri ihe ndị dị iche dịka aja ma ọ bụ nzu, nke a nwere ike ịbụ akara nke iron dị ala. Gwa onye ọrụ ahụike kama iri ihe ndị a.",
      "Ọ bụrụ na ụlọ ọgwụ nyere gị ọgwụ MMS (multiple micronutrient supplement), biko echefukwala ịṅụ otu kwa ụbọchị — ọ na-enye gị na nwa gị vitamin na mineral nke nri naanị nwere ike ghara inye n'uju.",
      "Gbalịa ịṅụ ọgwụ MMS gị n'otu oge kwa ụbọchị ka ọ bụrụ akụkụ nke omume gị — ọtụtụ ndị nne na-ahụ na ọ kacha mfe ozugbo ha risịrị nri.",
      "Ịṅụ ọgwụ MMS gị na nri, ma ọ bụ tupu ị lakpuo ụra, nwere ike inye aka ma ọ bụrụ na ọ na-eme ka afọ na-elu gị. Akwụsịla ịṅụ ya — kama gwa onye ọrụ ahụike.",
      "Nọgide na-aṅụ ọgwụ MMS gị kwa ụbọchị ọbụna mgbe ahụ dị gị mma. Ọ na-echebe uto nwa gị nwayọọ nwayọọ, ọ bụghị naanị ịgwọ ihe mgbaàmà.",
      "Ọgwụ MMS gị na-arụ ọrụ tinyere ezigbo nri — ọ naghị anọchi ya. Nọgide na-eri agwa, akwụkwọ nri, mkpụrụ osisi, na protein tinyere ịṅụ ọgwụ ahụ.",
      "Ọ bụrụ na ọgwụ MMS gị na-agwụ ma ọ bụ agwụọla, rịọ ka e nye gị ọzọ na nleta antenatal gị na-esote — gbalịa ka ị ghara ịhapụ ụbọchị n'etiti."
    ],
    "TIPS_BREASTFEEDING": [
      "Mmiri ara nne bụ nri kachasị mma maka nwa gị n'ọnwa 6 mbụ — ọ nwere ihe niile nwa gị chọrọ, gụnyere ihe ndị na-alụso ọrịa ọgụ.",
      "Inye nwa gị mmiri ara mgbe niile bụ ụzọ kachasị mkpa iji mee ka mmiri ara gị na-erubata nke ọma. Ụṅụọ mmiri iji mejuo ọṅụṅụ mmiri na-agụ gị ka ahụ gị nwee ike.",
      "Nye nwa gị mmiri ara mgbe ọ bụla ọ na-egosi na agụụ na-agụ ya — dịka mgbe ọ na-achọ ara ma ọ bụ na-etinye aka n'ọnụ. Ka ị na-enye ya mmiri ara mgbe niile, ka ahụ gị na-emepụta mmiri ara ka ukwuu.",
      "Iri ofe ugu ma ọ bụ waterleaf tinyere obere mmanụ nri na ahụekere na-enyere ahụ gị aka inweta nri dị mkpa maka ime mmiri ara.",
      "Anyala nwa gị mmiri nkiti, pap, ma ọ bụ nri ọzọ tupu ọ ruo ọnwa 6 — mmiri ara nne naanị ezuola, ọbụna n'oge okpomọkụ.",
      "Nwa gị na-enweta mmiri ara nke ọma ma ọ bụrụ na ọ na-eto nke ọma ma na-anyụ mmiri ọ dịkarịa ala ugboro 6 n'ụbọchị.",
      "Mmanụ nri (mmanụ anwụ) n'ofe gị na-enye Vitamin A nke na-abanye n'mmiri ara gị wee chebe auga nwa gị na ahụ ike ya.",
      "Iri nri nwere protein kwa ụbọchị — dịka agwa, azụ, ọkụkọ, ma ọ bụ anụ — na-enyere ahụ gị aka ime mmiri ara ma na-enye gị ike.",
      "Ọ bụrụ na ara gị siri ike ma ọ bụ na-afụ ụfụ, nye nwa gị ara mgbe niile. Nke a na-ebelata mgbu ma na-eme ka mmiri ara na-eru mfe.",
      "Mmiri aki oyibo, tiger nut milk na fura da nono bụ ihe ọṅụṅụ obodo na-enyere ụmụ nne na-enye ara aka n'ime mmiri ara.",
      "Inye ara na-enyere akpa nwa gị aka ịlaghachi n'ọnọdụ ya mgbe ị mụrụ nwa, ọ na-ebelatakwa ohere nke inweta kansa ụfọdụ — ọ mma maka gị n'onwe gị.",
      "Gaa n'ihu na-enye mmiri ara nne tinyere nri obodo site n'ọnwa 6 ruo mgbe ọ ruru afọ 2 ma ọ bụ karịa — mmiri ara nne ka na-enye nri na nchebe.",
      "Nri nwere iron dịka agwa, chi, na azụ sardine dị mkpa karịa maka ụmụ nne mgbe mụchara nwa.",
      "Calcium na-edobe ọkpụkpụ gị ike. Akwụkwọ nri, crayfish, soybean, na milk bụ nri obodo na-enye calcium n'ụzọ mfe.",
      "Ọ bụrụ na ịchọrọ ịpụ apụ ma ọ bụ laghachi n'ọrụ, ị nwere ike ịkụda mmiri ara gị ma dowe ya n'enweghị nsogbu maka nwa gị — jụọ dọkịta gị maka nkọwa.",
      "Kwọwa aka gị na ncha tupu ị na-enye ara ma ọ bụ tupu ịkwadebe nri nwa gị — ọ dị mfe mana ọ na-echebe unu abụọ.",
      "Ịda mbà ma ọ bụ ụjọ nwere ike ibelata mmiri ara gị nwa oge. Gbalịa izu ike, ị na-eku ume nwayọọ, ma jụọ enyemaka n'aka ezinụlọ mgbe ị nwere ike.",
      "Ọ dịghị mkpa nri pụrụ iche iji nweta ezigbo mmiri ara — naanị rie nri dị iche iche dị gị nso ma ṅụọ mmiri mgbe akpịrị na-akpọ gị nkụ.",
      "Ọ bụrụ na ị na-aṅụ ọgwụ ọ bụla, jụọ onye ọrụ ahụike ma ọ dị mma n'oge ị na-enye ara — ọtụtụ ọgwụ a na-ejikarị eme ihe dị mma.",
      "Ọ bụrụ na ara gị agbawaala ma ọ bụ na-afụ ụfụ, ọ na-abụkarị na nwa gị anaghị ejide ara nke ọma. Jụọ onye ọrụ ahụike ka o lelee otu nwa gị si ejide ya."
    ],
    "TIPS_BABY_0_6": [
      "Mmiri ara nne bụ naanị ihe nwa gị chọrọ n'ọnwa 6 mbụ — enweghị mmiri nkiti, pap, ma ọ bụ milk gwangwani. Ọ na-eme nchebe megide ọrịa ma na-akwado uto ụbụrụ.",
      "Nye nwa gị mmiri ara ara dịkarịa ala ugboro 8 ruo 12 kwa awa 24 n'izu mbụ — inye ara mgbe niile na-ewulite mmiri ara gị.",
      "Jide nwa gị n'ahụ gị ozugbo (skin-to-skin) dịka o kwere mee. Ọ na-edobe ha n'oku, dajụọ ha, ma na-agba inye ara ume.",
      "Ụbụrụ nwa gị na-eto nke mpụta ngwa ngwa ugbua. Mmiri ara nne nwere abụba na nri niile dị mkpa maka uto ụbụrụ dị mma.",
      "Anya tinyela shuga, mmanụ aṅụ, ma ọ bụ nnu n'ihe ọ bụla ị na-enye nwa gị nọ n'okpuru ọnwa 6. Ọkpụkpụ ha na usoro digestive ha adịghị njikere.",
      "Ọ bụrụ na nwa gị na-ehi ura karịa awa 4 n'usoro n'izu mbụ, kpọtee ha maka inye nri — ha chọrọ iri nri mgbe niile iji tolite nke ọma.",
      "Mmiri ara nne na-agbanwe n'ụbọchị dum na mgbe nwa gị na-eto — ahụ gị na-agbanwe mmiri ara mgbe niile iji mezuo mkpa nwa gị.",
      "Kwọwa aka gị na ncha tupu ị emetụ ma ọ bụ nye nwa gị nri — usoro nchebe ahụ ha ka na-ewuli ma ịdị ọcha dị oke mkpa n'ọnwa ndị a mbụ.",
      "Nwa na-ebe akwa anaghị apụta na agụụ na-agụ ya mgbe niile — o nwere ike chọ mgbanwe diaper, nkasi obi, ma ọ bụ ka ejide ya. Ị ga-amata ụdị ákwá nwa gị dị iche iche mgbe oge na-aga.",
      "Ọ dịghị mkpa inye nwa gị mmiri ahịhịa, ọgwụ ọdịnala, ma ọ bụ ọgwụ ezé tupu ọ ruo ọnwa 6 — mmiri ara nne naanị ezuola mkpa ya niile.",
      "Ọ bụrụ na nwa gị na-ekpo ọkụ, na-eri ara nke ọma, ma ọ bụ na-eyi ka ọ na-adịghị ike, buru ya gaa ụlọ ọrụ ahụike ozugbo — echela ka o zuo n'ụlọ."
    ],
    "TIPS_BABY_6_12": [
      "Nwa gị gbara bido iri nri siri ike n'ọnwa 6 tinyere mmiri ara nne. Bido n'nri dị mfe mụrụ mụrụ dịka pap, ji a dakarịrị adaka, ma ọ bụ agwa dakarịrị adaka.",
      "Nye nwa gị nri siri ike ugboro 2 ruo 3 n'ụbọchị n'etiti ọnwa 6 ruo 8, na-abawanye gaa ugboro 3 ruo 4 n'ụbọchị ka ọ na-eru ọnwa 9.",
      "Itinye obere mmanụ nri ma ọ bụ mmanụ ahụekere n'pap nwa gị na-enye ha abụba dị mkpa na ike ọzọ maka uto.",
      "Weta otu nri ọhụrụ n'oge ma chere kwanu 2 ruo 3 tupu itinye ọzọ — nke a na-enyere gị aka chọpụta nri na-anaghị amata afọ nwa gị.",
      "Ka ọ na-eru ọnwa 8, inti ka ukwuu n'ụmụaka nwere ike ijide nri aka dị mfe — gwada obere iberibe mkpụrụ osisi, karọọt esiri esi, ma ọ bụ ọkwá esiri esi.",
      "Ọkwá esiri esi dakarịrị adaka bụ otu n'nri kachasị mma ị nwere ike inye nwa gị site n'ọnwa 6 — ọ nwere protein, iron, na abụba mma.",
      "Crayfish dakarịrị adaka a tinyere n'pap nwa gị na-enye calcium na protein. Obere tupu ezuola.",
      "Mmiri ara nne ka dị mkpa nke ukwuu n'etiti ọnwa 6 ruo 12 — gaa n'ihu na-enye mmiri ara nne tinyere nri siri ike.",
      "Nwa gị chọrọ iri nri site n'ọ dịkarịa ala otu nri 5 dị iche iche kwa ụbọchị. Gbalịa tinye ọka, agwa ma ọ bụ ọkwá, akwụkwọ nri, mkpụrụ osisi, na obere anụ ma ọ bụ azụ.",
      "Zere inye nwa gị tii, ruwa 'ya'yan itace, abin sha mai zaƙi — mmiri nkiti na mmiri ara nne bụ naanị ihe ọṅụṅụ ha chọrọ.",
      "Chi (liver) a dakarịrị adaka ugboro otu ma ọ bụ ugboro abụọ n'izu bụ otu n'nri kachasị mma maka ụmụaka — ọ nwere iron, zinc, na Vitamin A.",
      "Ọ bụrụ na nwa gị gbanwere isi ma ọ bụ mechie ọnụ ya, amana ya taa nri. Gwada ọzọ mechaa ma ọ bụ nye nri ọzọ.",
      "Kwọwa aka gị ma hichaa ebe nri nwa gị tupu nri ọ bụla — nje si n'aka ma ọ bụ ngwá ọrụ na-adịghị ọcha bụ ihe na-akpatakarị afọ ọsịsa n'afọ ndị a.",
      "Bido na nri dị nnọọ dị larịị ma jiri nwayọọ gaa na nri dị njọ ka nwa gị na-amata iri nri — nke a na-enyere ya aka ịmụta ata nri.",
      "Obere nnu iodine na nri nwa gị site n'ọnwa 6 dị mma ma na-akwado uto ụbụrụ, mana zere itinye nnu ma ọ bụ shuga karịa nke ahụ.",
      "Nye nwa gị mmiri n'ime iko n'obere mmiri site n'ọnwa 6 — nke a dị iche na mmiri ara nne ma na-enyere ya aka ịmata ịṅụ site n'iko.",
      "Chekwaa nri ọ bụla akwadobere nwa gị n'ime ihe ọ dị ọcha nwere mkpuchi, jiri ya n'ime awa ole na ole — anaghị agbagharị ịkpọ nri ọkụ ọzọ."
    ],
    "TIPS_BABY_12_24": [
      "Ka ọ na-eru ọnwa 12 nwa gị nwere ike iri kalaria nri ezinụlọ — naanị mepụta na nri dị mfe, enweghị nnu pụrụ iche, ma bee ya n'iberibe ha nwere ike ijide.",
      "Gaa n'ihu na-enye mmiri ara nne tinyere nri ezinụlọ ruo mgbe nwa gị ruru afọ 2 ma ọ bụ karịa. Mmiri ara nne ka na-enye nri dị mkpa na nchebe.",
      "Nye nwa gị nri buru ibu ugboro 3 na nri mfe ugboro 1 ruo 2 kwa ụbọchị. Mkpụrụ osisi, ọkwá esiri esi, ma ọ bụ ahụekere bụ nhọrọ mma.",
      "Nri sitere n'anụmanụ dịka ọkwá, azụ, ọkụkọ, ma ọ bụ chi (liver) n'ọ dịkarịa ala ugboro otu n'ụbọchị na-enyere ụbụrụ na ahụ nwa gị aka itolite nke ọma.",
      "Akwụkwọ nri ndụ dịka ugu, spinach, na waterleaf nwere iron na Vitamin A. Tinye ha n'ofe nwa gị kwa ụbọchị.",
      "Zere inye nwa gị biskit, switi, nri e siri n'mmanụ, ma ọ bụ ihe ọṅụṅụ shuga — ha na-eme ka afọ ha ju n'enweghị nri gidi.",
      "Nwa gị chọrọ nri dị iche iche — gbalịa nye nri dị iche iche kwa ụbọchị ka ha mụta ịnụ ụtọ dị iche iche.",
      "Mkpụrụ osisi na akwụkwọ nri orange da yellow dịka pawpaw, mango, na karọọt nwere Vitamin A nke na-echebe nhụjuanya auga nwa gị na usoro nchebe.",
      "Tụọ arọ nwa gị kwa sarị n'ụlọ ọrụ ahụ ike kacha nso iji mepụta na ha na-eto nke ọma. Weta kaadi ahụ ike gị kwa oge.",
      "Ọ bụrụ na nwa gị ajụ nri ọhụrụ, gaa n'ihu na-enye ya n'obere adịghị — ụmụaka na-achọkarị ịhụ nri ugboro 8 ruo 10 tupu ha anabata ya.",
      "Agwa, cowpea, na soybean bụ nri protein dị ọnụ ala nke na- mma maka uto nwa gị. Daka ha nke ọma ma ọ bụ hazie n'ofe.",
      "Mmiri ara ehi, yoghurt, ma ọ bụ nono nwere ike inye dịka akụkụ nri site n'ọnwa 12 — ha na-enye calcium na protein maka ọkpụkpụ ike.",
      "Kwe ka nwatakịrị gị nwaa iri nri ya n'onwe ya jiri aka ma ọ bụ ngaji, ọbụna ọ bụrụ na ọ ga-agbasa — nke a na-ewuli onwe onye na mmekọrịta dị mma na nri.",
      "Sacha mkpụrụ osisi na akwụkwọ nri nke ọma ma kwọọ aka gị tupu ịkwadebe nri nwatakịrị gị iji belata ihe ize ndụ ọrịa afọ.",
      "Ojoko, ji, na akpu bụ nri ike dị mma maka nwatakịrị na-eto — jikọta ha na agwa, akwa, ma ọ bụ azụ maka nri zuru oke.",
      "Zere inye nwatakịrị gị mkpụrụ osisi zuru ezu, popcorn, ma ọ bụ akwụkwọ nri gbara ọkụ na-esighị nri nke nwere ike ime ka o loo ihe — kama ya, bee nri n'obere iberibe dị nro.",
      "Ọ bụrụ na nwatakịrị gị na-eri nri erughị eru dịka mbụ, na-ada mgbu oke, ma ọ bụ anaghị arata ọtụtụ arọ, buru ya gaa ụlọ ọrụ ahụike ka a lelee ya."
    ]
  },
  "yoruba": {
    "TIPS_PREGNANT": [
      "Jíjẹ ònjẹ tó ní iron púpọ̀ bíi ẹ̀wà, ẹ̀dọ̀, àti ẹfọ́ lójojúmọ́ ń giúp láti dènà ààbọ̀ ẹ̀jẹ̀ àti àìsan, ó sì ń ṣe ìrànlọ́wọ́ fún ìgbàgbọ́ ọmọ rẹ.",
      "Folate ṣe kókó púpọ̀ ní àkókò oyún — jẹ ẹ̀wà àti ẹfọ́ lágbára bíi ugu lójojúmọ́ láti giúp kwakwalwa àti eegun ẹ̀yìn ọmọ rẹ dàgbà daadaa.",
      "Ara rẹ ń fẹ́ ònjẹ sí i ní àkókò oyún. Gìyánjẹ́ láti jẹ ònjẹ míràn tàbí ònjẹ fẹ́rẹ́fẹ́ kan pẹ̀lú lójojúmọ́ — ẹ̀pà, ẹyin, tàbí eso jẹ́ àwọn àṣàyàn tó dára.",
      "Mímu omi tó tó lójojúmọ́ — ó kéré tán gíláàsì 8 — ń pa ọ́ mọ́ ní ìlanà tó dára, ó ń dènà àìlètọ̀ daadaa, ó sì ń ṣe ìrànlọ́wọ́ fún ààbò ara rẹ.",
      "Epo pupa nínú ọbẹ̀ rẹ jẹ́ alábàáṣe Vitamin A tó dára, eyí tó ń ṣe idabobo fún ojú ọmọ rẹ àti ààbò ara rẹ̀.",
      "Jíjẹ àwọn ònjẹ onírúurú lójojúmọ́ — ọka, ẹ̀wà, ẹfọ́, eso, àti obere ẹran tàbí ẹja — ń fún ọmọ rẹ ní ìbẹ̀rẹ̀ tó dára jù lọ.",
      "Calcium ń giúp eegun ọmọ rẹ dàgbà pẹ̀lú okun. Gìyánjẹ́ láti fi wàrà, yoghurt, ede (crayfish), tàbí soybean sí ònjẹ rẹ nígbà gbogbo.",
      "Má ṣe mu tii tàbí kọfị pẹ̀lú ònjẹ rẹ — wọn le dín adíẹ̀ ẹ̀jẹ̀ (iron) tí ara rẹ ń gbà kù. Maimakon bẹ́ẹ̀, fi obere omi lemon tàbí ọrọmbo sí i.",
      "Ìsinmi ṣe kókó gẹ́gẹ́ bí ònjẹ ní àkókò oyún. Gìyánjẹ́ láti sùn ó kéré tán wákàtí 8 ní alẹ́ àti láti sinmi ní ọ̀sán nígbà tó ba ṣe é ṣe.",
      "Tí o bá ń mọ̀ àrẹ̀ púpọ̀, ojú tó ń yí, tàbí àìlèmi daadaa, lọ sí ilé-ìwòsàn tó sunmọ́ ọ jù lọ — àwọn eyí le jẹ́ àmì àìtó ẹ̀jẹ̀ (anaemia).",
      "Jíjẹ ònjẹ kekeke nìgbà púpọ̀ yálà léte ń giúp tí o bá ń mọ̀ àìrora nínú afẹ́fẹ́. Gwada biskit gbigbẹ tàbí ẹ̀kọ kíkọ́ ní àárọ̀ kí o tó jẹ ònjẹ ńlá.",
      "Ọmọ rẹ ń fẹ́ iodine fún ìgbàgbọ́ kwakwalwa. Lo iyọ̀ iodine nínú sísè rẹ — ó rọrùn láti rà ó sì wà ní gbogbo ọjà.",
      "Zinc ń giúp ọmọ rẹ dàgbà ó sì ń ṣe ìrànlọ́wọ́ fún ààbò ara rẹ. Ẹ̀wà, ẹran nlá, àti ede (crayfish) jẹ́ ònjẹ lórílẹ̀-èdè Nàìjíríà tó ń fún ni ní zinc.",
      "Vitamin C ń giúp ara rẹ gba iron daadaa. Kí o fi tomato, ata, tàbí ọrọmbo sí ònjẹ rẹ jẹ́ ọ̀nà rọrùn láti rí èròjà púpọ̀ sí i.",
      "Má ṣe jẹ ònjẹ tó ni iyọ̀ púpọ̀ tàbí shuga púpọ̀ nígbà gbogbo ní àkókò oyún. Wọ́n le fa ìbúkù ó sì kò dára fún ọmọ rẹ.",
      "Wẹ ọwọ́ rẹ pẹ̀lú ọṣẹ kí o tó jẹun tàbí kí o tó se oúnjẹ — èyí ń ràn ọ́ lọ́wọ́ láti dènà àìsàn tí ó lè kan ìwọ àti ọmọ rẹ nígbà oyún.",
      "Mu oogun iron àti folic acid rẹ lójoojúmọ́ gẹ́gẹ́ bí òṣìṣẹ́ ìlera ṣe fún ọ, kódà bí ara rẹ bá dára — wọ́n ń ràn ọ́ lọ́wọ́ láti dènà àìsan ẹ̀jẹ̀ wọ́n sì ń ṣe àtìlẹyìn fún ìdàgbàsókè ọmọ rẹ.",
      "Rírí oòrùn díẹ̀ lára rẹ lójoojúmọ́ ń ràn ara rẹ lọ́wọ́ láti ṣe Vitamin D, èyí tí ó ṣe pàtàkì fún egungun rẹ àti ti ọmọ rẹ.",
      "Rí i dájú pé ẹran, ẹja, àti ẹyin ti jinná dáadáa kí o tó jẹ wọ́n — oúnjẹ tí kò jinná dáadáa lè ní kòkòrò tí ó léwu jù nígbà oyún.",
      "Máa lọ sí gbogbo ìpàdé ìtọ́jú oyún (antenatal) bí a ti ṣètò — wọ́n ń ràn ọ́ lọ́wọ́ láti mọ ìṣòro ní kíákíá, ó sì jẹ́ àkókò tó dára láti béèrè nípa oúnjẹ rẹ.",
      "Bí o bá ń fẹ́ jẹ ohun bí amọ̀ tàbí chalk, èyí lè jẹ́ àmì àìtó iron. Bá òṣìṣẹ́ ìlera sọ̀rọ̀ dípò kí o jẹ irú àwọn nǹkan bẹ́ẹ̀.",
      "Bí ilé-ìwòsàn bá fún ọ ní oogun MMS (multiple micronutrient supplement), jọ̀wọ́ má gbàgbé láti mu ọ̀kan lójoojúmọ́ — ó ń fún ìwọ àti ọmọ rẹ ní vitamin àti mineral tí oúnjẹ nìkan lè má pèsè ní kíkún.",
      "Gbìyànjú láti mu oogun MMS rẹ ní àkókò kan náà lójoojúmọ́ kí ó lè di ara ìṣesí rẹ — ọ̀pọ̀ ìyá ni ó rí i pé ó rọrùn jùlọ lẹ́yìn oúnjẹ.",
      "Mímu oogun MMS rẹ pẹ̀lú oúnjẹ, tàbí kí o tó sùn, lè ràn ọ́ lọ́wọ́ bí ó bá ń mú kí inú rẹ máa ru. Má ṣe dá mímu rẹ̀ dúró — dípò bẹ́ẹ̀, bá òṣìṣẹ́ ìlera sọ̀rọ̀.",
      "Máa mu oogun MMS rẹ lójoojúmọ́ kódà nígbà tí ara rẹ bá dára gan-an. Ó ń dáàbò bo ìdàgbàsókè ọmọ rẹ ní ìdákẹ́jẹ́ẹ́, kì í ṣe pé ó ń wo àmì àìsàn nìkan.",
      "Oogun MMS rẹ ń ṣiṣẹ́ pẹ̀lú oúnjẹ tó dára — kò rọ́pò rẹ̀. Máa jẹ ẹ̀wà, ewébẹ̀, èso, àti oúnjẹ protein pẹ̀lú mímu oogun náà.",
      "Bí oogun MMS rẹ bá ń parí tàbí ó ti tán, béèrè fún òmíràn ní ìpàdé ìtọ́jú oyún rẹ tó ń bọ̀ — gbìyànjú kí o má ṣe fo ọjọ́ kankan."
    ],
    "TIPS_BREASTFEEDING": [
      "Omi ọmu nikan ni ojúlówó ònjẹ tó dára jù lọ fún ọmọ rẹ ní oṣù mẹ́fà àkọ́kọ́ — ó ní gbogbo ohun tó ń fún ọmọ ní okun, pẹ̀lú àwọn èròjà tó ń gbógun ti àìsàn.",
      "Fífún ọmọ ní ọmu nígbà gbogbo ni ọ̀nà tó ṣe kókó jù lọ láti mú ki omi ọmu rẹ pọ̀ sí i. Rí i dásí pé o ń mu omi tó tó láti pa òùngbẹ rẹ mọ́ra ki ara rẹ le wà ní ìlanà tó dára.",
      "Máa fún ọmọ rẹ ní ọmu nígbà kígbà tó ba ń fi àmì ebi hàn — bíi kó máa ta orí sígbá tabi kó máa bu ọwọ́ rẹ̀ sẹ́nu. Bí o ṣe ń fún ọmọ ní ọmu sí i, bẹ́ẹ̀ ni ara rẹ ṣe ń ṣe omi ọmu sí i.",
      "Jíjẹ ọbẹ̀ ẹfọ́ ugu tàbí wọ̀tálífì pẹ̀lú epo pupa àti ẹ̀wà pẹ́kẹ́pẹ́kẹ́ máa ń fún ara rẹ ní èròjà tó mọ́ra láti mu omi ọmu rẹ pọ̀ sí i.",
      "Má ṣe fún ọmọ rẹ ní omi, ẹ̀kọ, tàbí ònjẹ kankan mìíràn kí o tó pe oṣù mẹ́fà — omi ọmu nìkan tó fún un, títí kan àkókò oyẹ́ tàbí ọ̀gẹẹ̀dẹ́ (ẹrù-oorùn).",
      "Ọmọ rẹ ń rí omi ọmu tó tó tó bá ń tó bi sí i ti ó sì ń tọ̀ àwọn pampers tàbí pákútá rẹ̀ ó kéré tán ẹ̀mẹ̀fà (6) ní ojúmọ́.",
      "Epo pupa tí o ń fi sí ọbẹ̀ rẹ ń fún ọmọ ní Vitamin A nipasẹ̀ omi ọmu rẹ, eròjà yìí sì ń da áàbò bò ojú àti ààbò ara ọmọ rẹ.",
      "Jíjẹ ònjẹ to ni protein lójojúmọ́ — bíi ẹ̀wà, ẹja, ẹyin, tàbí ẹran — ń giúp ara rẹ ṣe omi ọmu tó tó, ó sì ń fún ìwọ náà ní okun.",
      "Tí ọmu rẹ bá le tàbí tó ń ro ọ́, fún ọmọ rẹ ní ọmu lẹ́ẹ̀kọ̀ọ̀kan sí i. Ìyẹn máa ń dín ìbúkù kù, ó sì ń mú kí omi ọmu rẹ máa ṣàn daadaa.",
      "Wàrà ẹ̀bọ̀ (Tiger nut milk) àti Fura da nono jẹ́ abínibí ònjẹ tí àwọn ìyá tó ń fún ọmọ ní ọmu máa ń rí ẹ̀rọ̀ láti mú kí omi ọmu wọn pọ̀ sí i.",
      "Fífún ọmọ ní ọmu ń giúp ilé-ọmọ rẹ láti padà sí ipò rẹ̀ mgbe o mụ́rọ̀ tán, ó sì ń dín ewu àrùn jẹjẹrẹ kù fún ìwọ náà.",
      "Tẹ̀síwájú láti máa fún ọmọ rẹ ní omi ọmu pẹ̀lú ònjẹ gidi lati oṣù mẹ́fà títí ti ọmọ rẹ yóò fi pe ọdún méjì tàbí kọjá bẹ́ẹ̀ — omi ọmu ton fún un ní èròjà àti ààbò.",
      "Ònjẹ tó ní iron púpọ̀ bíi ẹ̀wà, ẹ̀dọ̀, àti ẹja sardine ṣe kókó fún àwọn ìyá tó ń fún ọmọ ní ọmu nítorí àwọn púpọ̀ máa ń sọ̀ iron nù mgbe wọn mụ́rọ̀ tán.",
      "Calcium ń ṣe idabobo fún eegun rẹ. Ede (crayfish), soybean, wàrà, àti yogurt jẹ́ ònjẹ ilẹ̀ wa tó rọrùn láti rà fún calcium.",
      "Tí o bá fẹ́ gbé ọmọ kúrò tàbí padà sí ẹnu osẹ́, o le pọn omi ọmu rẹ sílẹ̀ pẹ̀lú ìglé gíga fún ọmọ rẹ — bi oníṣègùn rẹ ní àgbègbè rẹ ní bí a ṣe ń ṣe é.",
      "Wẹ ọwọ́ rẹ pẹ̀lú ọṣẹ kí o tó fún ọmọ rẹ lọ́mú àti kí o tó pèsè oúnjẹ rẹ̀ — ìmọ́tótó rọrùn yìí ń dáàbò bo ẹ méjèèjì lọ́wọ́ àìsàn.",
      "Ìdààmú ọkàn tàbí ìbẹ̀rù lè dín omi ọmu rẹ kù fún ìgbà díẹ̀. Gbìyànjú láti sinmi, mí jẹjẹ, kí o sì béèrè ìrànlọ́wọ́ láti ọ̀dọ̀ ìdílé nígbà tí o bá lè ṣe é.",
      "Kò sí àìní oúnjẹ pàtàkì kan láti ní omi ọmu tó dára — kàn jẹ oúnjẹ oríṣiríṣi tó wà lọ́wọ́ rẹ kí o sì mu omi nígbà tí òùngbẹ bá ń gbẹ ọ́.",
      "Bí o bá ń mu oògùn kankan, béèrè lọ́wọ́ òṣìṣẹ́ ìlera bóyá ó dára láti mu nígbà tí o bá ń fún ọmọ lọ́mú — ọ̀pọ̀lọpọ̀ oògùn tí a máa ń mu ni ó dára.",
      "Bí ọmú rẹ bá ya tàbí ó ń dun ọ́, ó sábà máa ń jẹ́ pé ọmọ rẹ kò tí ì mú ọmú dáadáa. Béèrè lọ́wọ́ òṣìṣẹ́ ìlera láti ṣàyẹ̀wò bí ọmọ rẹ ṣe ń dì mú."
    ],
    "TIPS_BABY_0_6": [
      "Omi ọmu nìkan ni gbogbo ohun tí ọmọ rẹ n fẹ́ ní oṣù 6 àkọ́kọ́ — kò sí omi, kò sí ẹ̀kọ, kò sí madara gwangwani. Ó ń dáàbò bò àìsàn ó sì ń ṣe ìrànlọ́wọ́ fún ìgbàgbọ́ kwakwalwa.",
      "Fún ọmọ rẹ ní ọmu ó kéré tán ẹ̀mẹ̀ 8 sí 12 ní wákàtí 24 lọ́nà àkọ́kọ́ nínú àwọn ọ̀ṣẹ̀ àkọ́kọ́ — fífún ọmọ ní ọmu nígbà gbogbo ń kọ́ adíẹ̀ omi ọmu rẹ.",
      "Dí mu ọmọ rẹ mọ́ ara rẹ (skin-to-skin) gẹ́gẹ́ bí o ṣe le ṣe. Ó ń mú ki wọ́n mọ̀ ọ̀yẹ́, ó ń dín adánwò kù, ó sì ń gba fífún ọmọ ní ọmu nìyanju.",
      "Kwakwalwa ọmọ rẹ ń dàgbà pẹ̀lú spẹẹdị gíga ní ìsinsìnyí. Omi ọmu ní gbogbo abụba àti èròjà tó fẹ́ fún ìgbàgbọ́ kwakwalwa tó dára.",
      "Má ṣe fi shuga, oyin, tàbí iyọ̀ sí ohun kankan tí o ń fún ọmọ rẹ tí kò pe oṣù 6. Ọ̀fun wọn àti ìgùn ààbò kò tíì gba eyí.",
      "Tí ọmọ rẹ bá ń sùn kọjá wákàtí 4 ní tẹ̀léra nínú àwọn ọ̀ṣẹ̀ àkọ́kọ́, jí wọn láti fún wọn ní ònjẹ — wọ́n ń fẹ́ jẹ ònjẹ nígbà gbogbo láti dàgbà daadaa.",
      "Omi ọmu ń pààrọ̀ nínú ọjọ́ àti bí ọmọ rẹ ṣe ń dàgbà — ara rẹ ń ṣètò omi ọmu nígbà gbogbo láti ba àwọn gba ti ọmọ rẹ mu.",
      "Wẹ ọwọ́ rẹ pẹ̀lú ọṣẹ kí o tó fọwọ́ kan tàbí kí o tó fún ọmọ rẹ ní oúnjẹ — ètò ààbò ara wọn ṣì ń dàgbà, ìmọ́tótó sì ṣe pàtàkì gan-an ní àwọn oṣù àkọ́kọ́ wọ̀nyí.",
      "Ọmọ tí ń sunkún kò ní túmọ̀ sí pé ebi ń pa á nígbà gbogbo — ó lè nílò ìyípadà diaper, ìtùnú, tàbí kí a gbé e mọ́ra. Ìwọ yóò kọ́ àwọn oríṣiríṣi ẹkún ọmọ rẹ ní àkókò.",
      "Kò sí àìní láti fún ọmọ rẹ ní omi ewéko, oogun ìbílẹ̀, tàbí oogun eyín kí o tó pe oṣù 6 — omi ọmu nìkan ló tó fún gbogbo àìní rẹ̀.",
      "Bí ọmọ rẹ bá ní ibà, tí kò lè mu ọmu dáadáa, tàbí tí ó dàbí ẹni tí kò ní agbára rárá, gbé e lọ sí ilé-ìwòsàn lẹ́sẹ̀kẹsẹ̀ — má ṣe dúró ní ilé."
    ],
    "TIPS_BABY_6_12": [
      "Ọmọ rẹ ti gba láti bẹ̀rẹ̀ ònjẹ gidi ní oṣù 6 pẹ̀lú omi ọmu. Bẹ̀rẹ̀ pẹ̀lú ònjẹ fẹ́rẹ́fẹ́ kíkọ́ bíi ẹ̀kọ, iṣan ji kíkọ́, tàbí ẹ̀wà kíkọ́.",
      "Fún ọmọ rẹ ní ònjẹ gidi ẹ̀mẹ̀ 2 sí 3 ní ojúmọ́ nínú oṣù 6 sí 8, ó ń pọ̀ sí ẹ̀mẹ̀ 3 sí 4 ní ojúmọ́ nínú oṣù 9.",
      "Fi obere epo pupa tàbí ẹ̀pà kíkọ́ sí ẹ̀kọ ọmọ rẹ ń fún wọn ní abụba ṣe kókó àti okun púpọ̀ sí i fún ìgbàgbọ́.",
      "Mú ònjẹ ọ̀tọ̀ kan wá ní àkókò kan náà ti o sì chere ọjọ́ 2 sí 3 kí o tó fi míràn sí i — eyí ń giúp ọ láti mọ̀ ònjẹ tí kò ba afẹ́fẹ́ ọmọ rẹ mu.",
      "Ní oṣù 8, ọ̀pọ̀lọpọ̀ àwọn ọmọ le lo ònjẹ ọwọ́ fẹ́rẹ́fẹ́ — gwada obere eso fẹ́rẹ́fẹ́, karọọt esiri esi, tàbí ẹyin kíkọ́.",
      "Ẹyin kíkọ́ jẹ́ ọ̀kan nínú ònjẹ tó dára jù lọ tí o le fún ọmọ rẹ lati oṣù 6 — ó ní protein, iron, àti abụba mma púpọ̀.",
      "Ede (crayfish) kíkọ́ tí o fi sí ẹ̀kọ ọmọ rẹ ń fún un ní calcium àti protein. Obere pinch tó fún un.",
      "Omi ọmu ka ṣe kókó púpọ̀ nínú oṣù 6 sí 12 — tẹ̀síwájú láti fún ní omi ọmu pẹ̀lú ònjẹ gidi.",
      "Ọmọ rẹ ń fẹ́ jẹ ònjẹ lati ó kéré tán ònjẹ group 5 daban-daban lójojúmọ́. Gìyánjẹ́ láti fi ọka, ẹ̀wà tàbí ẹyin, ẹfọ́, eso, àti obere ẹran tàbí ẹja sí i.",
      "Zere inye nwa gị tii, ruwa 'ya'yan itace, abin sha mai zaƙi — omi nkiti àti omi ọmu ni ònjẹ nìkan tí wọ́n ń fẹ́.",
      "Ẹ̀dọ̀ kíkọ́ lẹ́ẹ̀kan tàbí ẹ̀mẹ̀fà ní ọ̀ṣẹ̀ jẹ́ ọ̀kan nínú ònjẹ tó dára jù lọ fún àwọn ọmọ — ó ní iron, zinc, àti Vitamin A púpọ̀. Daka a daadaa.",
      "Tí ọmọ rẹ bá yí orí tàbí ti ẹnukẹ́ rẹ̀, má ṣe fi ipá fún un ní ònjẹ. Gwada ọzọ mechaa tàbí fún un ní ònjẹ míràn.",
      "Wẹ ọwọ́ rẹ kí o sì fọ ibi tí ọmọ rẹ ti ń jẹun mọ́ kí oúnjẹ kọ̀ọ̀kan tó dé — kòkòrò láti ọwọ́ tàbí ohun èlò tí kò mọ́ ni ó sábà máa ń fa ìgbẹ́ gbuuru ní ọjọ́ orí yìí.",
      "Bẹ̀rẹ̀ pẹ̀lú oúnjẹ tí ó rọ̀ dáadáa kí o sì máa fi kún kúrò díẹ̀díẹ̀ bí ọmọ rẹ ṣe ń mọ bí a ṣe ń jẹun — èyí ń ràn án lọ́wọ́ láti kọ́ bí a ṣe ń jẹ oúnjẹ líle.",
      "Iyọ̀ iodine díẹ̀ nínú oúnjẹ ọmọ rẹ láti oṣù 6 wà ní àìléwu, ó sì ń ṣe àtìlẹyìn fún ìdàgbàsókè ọpọlọ, ṣùgbọ́n yẹra fún fífi iyọ̀ tàbí ṣúgà kún ju bẹ́ẹ̀ lọ.",
      "Fún ọmọ rẹ ní omi nínú ago ní obere sips nígbà oúnjẹ láti oṣù 6 — èyí yàtọ̀ sí omi ọmu, ó sì ń ràn án lọ́wọ́ láti mọ bí a ṣe ń mu omi nínú ago.",
      "Fi oúnjẹ tí a ti pèsè fún ọmọ rẹ sínú àwo tó mọ́ tí ó ní ìbòrí, kí o sì lò ó láàrín wákàtí díẹ̀ — má ṣe kó oúnjẹ gbóná ju ẹ̀ẹ̀kan lọ."
    ],
    "TIPS_BABY_12_24": [
      "Ní oṣù 12 ọmọ rẹ le jẹ ọ̀pọ̀lọpọ̀ ònjẹ ẹbí — naanị mepụta pé ònjẹ rọrùn, kò ní iyọ̀ púpọ̀, ti o sì bee e nínú obere iberibe tí wọ́n le jide.",
      "Tẹ̀síwájú láti fún ní omi ọmu pẹ̀lú ònjẹ ẹbí títí ti ọmọ rẹ yóò fi pe ọdún 2 tàbí kọjá bẹ́ẹ̀. Omi ọmu ka ń fún un ní ònjẹ àti ààbò.",
      "Fún ọmọ rẹ ní ònjẹ ńlá ẹ̀mẹ̀ 3 àti ònjẹ fẹ́rẹ́fẹ́ ẹ̀mẹ̀ 1 sí 2 lójojúmọ́. Eso, ẹyin esiri esi, tàbí ẹ̀pà jẹ́ àṣàyàn tó dára.",
      "Ònjẹ eranko bíi ẹyin, ẹja, ọkụkọ, tàbí ẹ̀dọ̀ ó kéré tán ẹ̀mẹ̀fà ní ojúmọ́ ń giúp kwakwalwa àti ara ọmọ rẹ dàgbà daadaa.",
      "Ẹfọ́ lágbára bíi ugu, spinach, àti waterleaf ní iron àti Vitamin A púpọ̀. Fi wọ́n sí ọbẹ̀ ọmọ rẹ lójojúmọ́.",
      "Má ṣe fún ọmọ rẹ ní biskit, switi, ònjẹ e siri n'mmanụ, tàbí abin sha shuga — wọ́n ń kún afẹ́fẹ́ wọn n'enweghị ònjẹ gidi.",
      "Ọmọ rẹ ń fẹ́ ònjẹ onírúurú — gìyánjẹ́ láti fún ní ònjẹ daban-daban lójojúmọ́ láti mọ̀ ịnụ ụtọ dị iche iche.",
      "Eso àti ẹfọ́ orange da yellow bíi pawpaw, mango, àti karọọt ní Vitamin A eyí tó ń ṣe idabobo fún ojú ọmọ rẹ àti ààbò ara.",
      "Tụọ arọ ọmọ rẹ lójojúmọ́ sarị ní ilé-ìwòsàn tó sunmọ́ ọ jù lọ láti mepụta pé wọ́n ń dàgbà daadaa. Weta kadi ahụ ike gị ní gbogbo oge.",
      "Tí ọmọ rẹ bá ajụ ònjẹ ọ̀tọ̀, tẹ̀síwájú láti fún un nínú obere adịghị — àwọn ọmọ ń fẹ́ rí ònjẹ ẹ̀mẹ̀ 8 sí 10 kí wọ́n tó anabata ya.",
      "Ẹ̀wà, cowpea, àti soybean jẹ́ ònjẹ protein tó rọrùn láti rà eyí tó dára fún ìgbàgbọ́ ọmọ rẹ. Daka ha daadaa tàbí hazie n'ofe.",
      "Madara, yoghurt, tàbí nono le wà ní inye gẹ́gẹ́ bí ònjẹ lati oṣù 12 — wọ́n ń fún ni ní calcium àti protein fún eegun ike.",
      "Jẹ́ kí ọmọ rẹ gbìyànjú láti jẹun fúnra rẹ̀ pẹ̀lú ọwọ́ tàbí sibi, kódà tí yóò bá tú ká — èyí ń kọ́ ọ ní òmìnira àti ìbáṣepọ̀ tó dára pẹ̀lú oúnjẹ.",
      "Fọ èso àti ewébẹ̀ dáadáa kí o sì wẹ ọwọ́ rẹ kí o tó pèsè oúnjẹ ọmọ rẹ láti dín ewu àìsàn inú kù.",
      "Ọ̀gẹ̀dẹ̀, iṣu, àti gbaguda jẹ́ oúnjẹ agbára tó dára fún ọmọ tó ń dàgbà — pọ̀ wọ́n mọ́ ẹ̀wà, ẹyin, tàbí ẹja fún oúnjẹ tó pé.",
      "Yẹra fún fífún ọmọ rẹ ní ẹ̀pà odidi, popcorn, tàbí ewébẹ̀ tí kò se tí ó le tí ó lè mú kí ó fún — dípò bẹ́ẹ̀, gé oúnjẹ sí àwọn ege kékeré tí ó rọ̀.",
      "Bí ọmọ rẹ bá ń jẹun díẹ̀ ju bí ó ti ń jẹ tẹ́lẹ̀ lọ, tí ó rẹ̀ ẹ́ gan-an, tàbí tí kò ń pọ̀ sí i lára, gbé e lọ sí ilé-ìwòsàn fún ìṣàyẹ̀wò."
    ]
  }
}